// <auto-generated />
using System;
using MentoringProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MentoringProject.Infrastructure.Migrations
{
    [DbContext(typeof(DbProjectContext))]
    [Migration("20220207191404_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MentoringProject.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cdfe332-bd96-4b20-9895-2bbb3bc13e85"),
                            Brand = "BMW",
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("37ceaac3-1594-401f-bdf4-b905bdc594ca"),
                            Brand = "Mercedes",
                            Color = "Black"
                        },
                        new
                        {
                            Id = new Guid("689283d4-87ae-4f1f-b64b-6babd9f5773a"),
                            Brand = "Nissan",
                            Color = "White"
                        });
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0887def0-465e-458a-af06-77ff184fbec1"),
                            FirstName = "Tom",
                            LastName = "Wolker"
                        },
                        new
                        {
                            Id = new Guid("240886dd-049b-4796-9efd-cbf2c8909937"),
                            FirstName = "Adam",
                            LastName = "Wolker"
                        },
                        new
                        {
                            Id = new Guid("cd3f8856-9b1f-4324-840f-921117fb8304"),
                            FirstName = "Alice",
                            LastName = "Wolker"
                        });
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.OwnerCar", b =>
                {
                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OwnerId", "CarId");

                    b.HasIndex("CarId");

                    b.ToTable("UserCars");
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.OwnerCar", b =>
                {
                    b.HasOne("MentoringProject.Domain.Entities.Car", "Car")
                        .WithMany("UserCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentoringProject.Domain.Entities.Owner", "Owner")
                        .WithMany("OwnersCars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.Car", b =>
                {
                    b.Navigation("UserCars");
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.Owner", b =>
                {
                    b.Navigation("OwnersCars");
                });
#pragma warning restore 612, 618
        }
    }
}
