// <auto-generated />
using System;
using MentoringProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentoringProject.Infrastructure.Migrations
{
    [DbContext(typeof(DbProjectContext))]
    [Migration("20220211231606_AddIdToOwnerCar")]
    partial class AddIdToOwnerCar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MentoringProject.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8697e51-6996-47fe-aa73-421d4384b8ac"),
                            Brand = "BMW",
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("089582de-6715-48dd-93d6-b011a3a68528"),
                            Brand = "Mercedes",
                            Color = "Black"
                        },
                        new
                        {
                            Id = new Guid("883df809-7943-4e06-91b9-cd3ed6eb8120"),
                            Brand = "Nissan",
                            Color = "White"
                        });
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("18b0d7ed-c4ca-409f-a2db-e2ef4b914a97"),
                            FirstName = "Tom",
                            LastName = "Wolker"
                        },
                        new
                        {
                            Id = new Guid("9cedd152-67b9-44f2-bd5d-524681b4bde1"),
                            FirstName = "Adam",
                            LastName = "Wolker"
                        },
                        new
                        {
                            Id = new Guid("b270753a-b4cb-4bd8-be8c-5f3bf701cec9"),
                            FirstName = "Alice",
                            LastName = "Wolker"
                        });
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.OwnerCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasAlternateKey("OwnerId", "CarId");

                    b.HasIndex("CarId");

                    b.ToTable("OwnerCars");
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.OwnerCar", b =>
                {
                    b.HasOne("MentoringProject.Domain.Entities.Car", "Car")
                        .WithMany("UserCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentoringProject.Domain.Entities.Owner", "Owner")
                        .WithMany("OwnersCars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.Car", b =>
                {
                    b.Navigation("UserCars");
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.Owner", b =>
                {
                    b.Navigation("OwnersCars");
                });
#pragma warning restore 612, 618
        }
    }
}
