// <auto-generated />
using System;
using MentoringProject.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MentoringProject.Infrastructure.Migrations
{
    [DbContext(typeof(DbProjectContext))]
    partial class DbProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MentoringProject.Domain.Entities.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5a5ccf8-280c-4341-a9e2-678877a432df"),
                            Brand = "BMW",
                            Color = "Red"
                        },
                        new
                        {
                            Id = new Guid("589dfdf0-60bd-4854-a7ee-91d6b30dbae9"),
                            Brand = "Mercedes",
                            Color = "Black"
                        },
                        new
                        {
                            Id = new Guid("d3dbee01-5eaa-4c80-9365-04cd007be277"),
                            Brand = "Nissan",
                            Color = "White"
                        });
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d41b120-9dbf-48df-8325-2f9c490cf585"),
                            FirstName = "Tom",
                            LastName = "Wolker"
                        },
                        new
                        {
                            Id = new Guid("ca67e360-bc52-4e41-9e0a-5ff6d40b1ff4"),
                            FirstName = "Adam",
                            LastName = "Wolker"
                        },
                        new
                        {
                            Id = new Guid("a13ae253-bd19-400d-8c74-fabb31f0fb45"),
                            FirstName = "Alice",
                            LastName = "Wolker"
                        });
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.OwnerCar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<Guid>("CarId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.HasIndex("OwnerId");

                    b.ToTable("OwnerCars");
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.OwnerCar", b =>
                {
                    b.HasOne("MentoringProject.Domain.Entities.Car", "Car")
                        .WithMany("OwnerCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MentoringProject.Domain.Entities.Owner", "Owner")
                        .WithMany("OwnersCars")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.Car", b =>
                {
                    b.Navigation("OwnerCars");
                });

            modelBuilder.Entity("MentoringProject.Domain.Entities.Owner", b =>
                {
                    b.Navigation("OwnersCars");
                });
#pragma warning restore 612, 618
        }
    }
}
